### ISSUE TITLE
question about your Hierarchical Coupling layer, is it an strictly invertible layer?

### ISSUE THREAD

**Issue by leepms** [WeichenFan/HierarchyFlow#2]
**thanks for your work. You have wroten very good paper and support code soonly.

Besides , I have read your early paper 《Styleflow for content-fixed image to image translation
》 which describes the flow-based style transfer method very informatively and is one of the best papers in my opinion.

However, I cannot get the sense that this Hierarychical Coupling layer is an invertible layer like other norm flow structure (like in GLOW)
Could you please give me more description or proof?**

**Comment by WeichenFan** [comment]
Hi leepms,

Thank you for your interest. :)

You can check out this figure:
![image](https://github.com/WeichenFan/HierarchyFlow/assets/112800544/ca21422b-e7c8-49b4-8f7c-78ae14a03d8d)

The AdaIN technique applied at each layer is the same as our previous work. The affine tensor calculated by the affine-net is kept during the backward pass.

Simply comment out this line https://github.com/WeichenFan/HierarchyFlow/blob/main/model/network/hf.py#L287, and you will find the output is the same as the input.

**Comment by minh-nguyenhoang** [comment]
@WeichenFan I have check your code and find that your hierarchy layer is not strictly reversible, as the reverse pass is wrong.
The first part `self.fixed_weight*(tmp_out + input[:, (i-1)*self.in_channel:i*self.in_channel])` with `self.fixed_weight = 0.5` is equivalent to ` input[:, (i-1)*self.in_channel:i*self.in_channel]` (so basically this would make the reverse pass parralelizable). 
The second part `feature[:, (i-1)*self.in_channel:i*self.in_channel]*(1-self.fixed_weight)` doesn't need a multiplier of `(1-self.fixed_weight)` as your forward pass don't have it.

**Comment by WeichenFan** [comment]
> @WeichenFan I have check your code and find that your hierarchy layer is not strictly reversible, as the reverse pass is wrong. The first part `self.fixed_weight*(tmp_out + input[:, (i-1)*self.in_channel:i*self.in_channel])` with `self.fixed_weight = 0.5` is equivalent to ` input[:, (i-1)*self.in_channel:i*self.in_channel]` (so basically this would make the reverse pass parralelizable). The second part `feature[:, (i-1)*self.in_channel:i*self.in_channel]*(1-self.fixed_weight)` doesn't need a multiplier of `(1-self.fixed_weight)` as your forward pass don't have it.

---
Thanks for your interest.

The forward pass does not require multiplying with a weight. The weight is only used during the backward pass in order to fuse the content & style (w/ AdaIN activated)
<img width="1024" alt="image" src="https://github.com/WeichenFan/HierarchyFlow/assets/112800544/080d2ab9-db98-4956-a9bf-6c34e9f40c03">

Without AdaIN, the fused two parts are the same. Therefore, the weights are used in this situation. However, when the AdaIN is used, the goal is not to reconstruct the input image but to achieve style transfer. In this manner, the forward and backward are not fully reversible, since part of the information has been modified.

**Comment by minh-nguyenhoang** [comment]
> > @WeichenFan I have check your code and find that your hierarchy layer is not strictly reversible, as the reverse pass is wrong. The first part `self.fixed_weight*(tmp_out + input[:, (i-1)*self.in_channel:i*self.in_channel])` with `self.fixed_weight = 0.5` is equivalent to ` input[:, (i-1)*self.in_channel:i*self.in_channel]` (so basically this would make the reverse pass parralelizable). The second part `feature[:, (i-1)*self.in_channel:i*self.in_channel]*(1-self.fixed_weight)` doesn't need a multiplier of `(1-self.fixed_weight)` as your forward pass don't have it.
> 
> Thanks for your interest.
> 
> The forward pass does not require multiplying with a weight. The weight is only used during the backward pass in order to fuse the content & style (w/ AdaIN activated) <img alt="image" width="1024" src="https://private-user-images.githubusercontent.com/112800544/344861021-080d2ab9-db98-4956-a9bf-6c34e9f40c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODk4MTMsIm5iZiI6MTcxOTg4OTUxMywicGF0aCI6Ii8xMTI4MDA1NDQvMzQ0ODYxMDIxLTA4MGQyYWI5LWRiOTgtNDk1Ni1hOWJmLTZjMzRlOWY0MGMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwMzA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjJjNzAzZmNmNjFjZGFjNmY4NTcyYTI3YTUxYzM1NDQzYWJlZjAyMWU0NGJjY2EwZTFlNWNhYzMwNzM5MDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._21FWXrZFKaH6OSFYOJEHODElRLp7dIWim1qiNzols0">
> 
> Without AdaIN, the fused two parts are the same. Therefore, the weights are used in this situation. However, when the AdaIN is used, the goal is not to reconstruct the input image but to achieve style transfer. In this manner, the forward and backward are not fully reversible, since part of the information has been modified.

Yes I have tried with the version without AdaIN and by using the weight, I can't achieve the invertibility. So is your point that you don't want this layer to be strictly invertible (if no style is used, only the content), but the backward pass should balance out the content feature and the style feature?
