### ISSUE TITLE
train with custom dataset

### ISSUE THREAD

**Issue by blackjacket996** [WeichenFan/HierarchyFlow#3]
Hey, thx for great work! what should I do if I wanna train a model using my own dataset? what I need?

**Comment by jhchenjh** [comment]
Hi Thanks for your interest.

To train a model with your own dataset,
1. prepare your data and generate data list file, where each line of the list file represents one image path in your dataset, you may refer to the given example of GTA2Cityscapes
2. modify the list paths and root paths of your data in the `dataset` part of the config file.
3. you may adjust other training parameters in the config file according to your experiment results.

Thank you.
